/-!
# The effect signature functor

An operation signature is `Op : Type → Type → Type 1` — `Op I O` is an operation taking an input
`I` and returning an `O`.  `Effect Op` is the functor it generates: one effect layer returning `O`
is an operation `Op I O` packaged with its input `I`.  This is what a `Comp`'s `vis` node carries.
-/

namespace Freigen

/-- The functor generated by an operation signature `Op`: an operation together with its input. -/
inductive Effect (Op : Type → Type → Type 1) : Type → Type 1 where
  | mk {I O : Type} : Op I O → I → Effect Op O

end Freigen
