/-!
# The free monad and freer-monad effects

The plain free monad `Free F` (with its `Monad` instance and `foldFree`), and the freer-monad
*effect functor* `Effect Op` generated by an operation signature `Op : Type → Type → Type 1`
over plain Lean types — `Op`/`Effect` know nothing about the AST's object-type universe.
-/

inductive Free (F : Type u → Type v) (α : Type u): Type _
| Pure : α → Free F α
| Impure : ∀{x}, F x -> (x -> Free F α) -> Free F α

def freeBind {F : Type u → Type v} {α β : Type u} (a : Free F α) (f : α → Free F β) : Free F β :=
  match a with
  | Free.Pure x => f x
  | Free.Impure a f' => Free.Impure a (fun x => freeBind (f' x) f)

/-- Right identity for the free monad. -/
theorem freeBind_pure {F : Type u → Type v} {α : Type u} (m : Free F α) :
    freeBind m Free.Pure = m := by
  induction m with
  | Pure a => rfl
  | Impure e c ih => simp only [freeBind]; congr 1; funext x; exact ih x

instance {F : Type u → Type v} : Monad (Free F) where
  pure := Free.Pure
  bind := freeBind

@[simp] theorem free_pure_eq {F : Type u → Type v} {α : Type u} (a : α) :
    (pure a : Free F α) = Free.Pure a := rfl

@[simp] theorem free_bind_eq {F : Type u → Type v} {α β : Type u}
    (m : Free F α) (f : α → Free F β) : m >>= f = freeBind m f := rfl

def foldFree [Monad M] (x : Free F α) (f : ∀{x}, F x → M x): M α := match x with
  | Free.Pure x => pure x
  | Free.Impure a f' => f a >>= fun x => foldFree (f' x) f

namespace Freigen

/-! ## The effect signature and its derived functor -/

/-- The freer-monad functor generated by an operation signature `Op` over plain Lean types:
    one effect layer returning `O` is some operation `Op I O` packaged with its input `I`.
    `Op` knows nothing about `Tp` — the AST threads the object types in (see `Exp.op`). -/
inductive Effect (Op : Type → Type → Type 1) : Type → Type 1 where
  | mk {I O : Type} : Op I O → I → Effect Op O

end Freigen
